<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Table_geo_country {
	/**
	 * !!! CAUTION !!!
	 * 
	 * Don't change the table name and class name because to important to seeder system
	 * 
	 * if you want to change the table name, copy your script code in this file
	 * remove this file with this bash 
	 * 
	 * php index.php Migration remove {table name}
	 * 
	 * then create new database with migration bash and paste you code before
	 */

	private $CI;

	public function __construct(){
		$this->CI =& get_instance();

        $this->CI->load->model('mc');
        $this->CI->load->library('Schema');
	}

	public function migrate(){
		$schema = $this->CI->schema->create_table('geo_country');
        $schema->increments('countryId', ['length' => '11']);
        $schema->string('countryName', ['length' => '130']);
        $schema->string('countryIsoCode2', ['length' => '2']);
        $schema->string('countryIsoCode3', ['length' => '3']);
        $schema->integer('countryStatus', ['type' => 'TINYINT', 'length' => '1', 'unsigned' => TRUE]);
        $schema->integer('countryDeleted', ['length' => '11', 'unsigned' => TRUE]);
        $schema->run();
	}

	public function seeder(){
		$arr = [
            ['countryId' => '1', 'countryName' => 'Afghanistan', 'countryIsoCode2' => 'AF', 'countryIsoCode3' => 'AFG', 'countryStatus' => '1'],
            ['countryId' => '2', 'countryName' => 'Albania', 'countryIsoCode2' => 'AL', 'countryIsoCode3' => 'ALB', 'countryStatus' => '1'],
            ['countryId' => '3', 'countryName' => 'Algeria', 'countryIsoCode2' => 'DZ', 'countryIsoCode3' => 'DZA', 'countryStatus' => '1'],
            ['countryId' => '4', 'countryName' => 'American Samoa', 'countryIsoCode2' => 'AS', 'countryIsoCode3' => 'ASM', 'countryStatus' => '1'],
            ['countryId' => '5', 'countryName' => 'Andorra', 'countryIsoCode2' => 'AD', 'countryIsoCode3' => 'AND', 'countryStatus' => '1'],
            ['countryId' => '6', 'countryName' => 'Angola', 'countryIsoCode2' => 'AO', 'countryIsoCode3' => 'AGO', 'countryStatus' => '1'],
            ['countryId' => '7', 'countryName' => 'Anguilla', 'countryIsoCode2' => 'AI', 'countryIsoCode3' => 'AIA', 'countryStatus' => '1'],
            ['countryId' => '8', 'countryName' => 'Antarctica', 'countryIsoCode2' => 'AQ', 'countryIsoCode3' => 'ATA', 'countryStatus' => '1'],
            ['countryId' => '9', 'countryName' => 'Antigua and Barbuda', 'countryIsoCode2' => 'AG', 'countryIsoCode3' => 'ATG', 'countryStatus' => '1'],
            ['countryId' => '10', 'countryName' => 'Argentina', 'countryIsoCode2' => 'AR', 'countryIsoCode3' => 'ARG', 'countryStatus' => '1'],
            ['countryId' => '11', 'countryName' => 'Armenia', 'countryIsoCode2' => 'AM', 'countryIsoCode3' => 'ARM', 'countryStatus' => '1'],
            ['countryId' => '12', 'countryName' => 'Aruba', 'countryIsoCode2' => 'AW', 'countryIsoCode3' => 'ABW', 'countryStatus' => '1'],
            ['countryId' => '13', 'countryName' => 'Australia', 'countryIsoCode2' => 'AU', 'countryIsoCode3' => 'AUS', 'countryStatus' => '1'],
            ['countryId' => '14', 'countryName' => 'Austria', 'countryIsoCode2' => 'AT', 'countryIsoCode3' => 'AUT', 'countryStatus' => '1'],
            ['countryId' => '15', 'countryName' => 'Azerbaijan', 'countryIsoCode2' => 'AZ', 'countryIsoCode3' => 'AZE', 'countryStatus' => '1'],
            ['countryId' => '16', 'countryName' => 'Bahamas', 'countryIsoCode2' => 'BS', 'countryIsoCode3' => 'BHS', 'countryStatus' => '1'],
            ['countryId' => '17', 'countryName' => 'Bahrain', 'countryIsoCode2' => 'BH', 'countryIsoCode3' => 'BHR', 'countryStatus' => '1'],
            ['countryId' => '18', 'countryName' => 'Bangladesh', 'countryIsoCode2' => 'BD', 'countryIsoCode3' => 'BGD', 'countryStatus' => '1'],
            ['countryId' => '19', 'countryName' => 'Barbados', 'countryIsoCode2' => 'BB', 'countryIsoCode3' => 'BRB', 'countryStatus' => '1'],
            ['countryId' => '20', 'countryName' => 'Belarus', 'countryIsoCode2' => 'BY', 'countryIsoCode3' => 'BLR', 'countryStatus' => '1'],
            ['countryId' => '21', 'countryName' => 'Belgium', 'countryIsoCode2' => 'BE', 'countryIsoCode3' => 'BEL', 'countryStatus' => '1'],
            ['countryId' => '22', 'countryName' => 'Belize', 'countryIsoCode2' => 'BZ', 'countryIsoCode3' => 'BLZ', 'countryStatus' => '1'],
            ['countryId' => '23', 'countryName' => 'Benin', 'countryIsoCode2' => 'BJ', 'countryIsoCode3' => 'BEN', 'countryStatus' => '1'],
            ['countryId' => '24', 'countryName' => 'Bermuda', 'countryIsoCode2' => 'BM', 'countryIsoCode3' => 'BMU', 'countryStatus' => '1'],
            ['countryId' => '25', 'countryName' => 'Bhutan', 'countryIsoCode2' => 'BT', 'countryIsoCode3' => 'BTN', 'countryStatus' => '1'],
            ['countryId' => '26', 'countryName' => 'Bolivia', 'countryIsoCode2' => 'BO', 'countryIsoCode3' => 'BOL', 'countryStatus' => '1'],
            ['countryId' => '27', 'countryName' => 'Bosnia and Herzegovina', 'countryIsoCode2' => 'BA', 'countryIsoCode3' => 'BIH', 'countryStatus' => '1'],
            ['countryId' => '28', 'countryName' => 'Botswana', 'countryIsoCode2' => 'BW', 'countryIsoCode3' => 'BWA', 'countryStatus' => '1'],
            ['countryId' => '29', 'countryName' => 'Bouvet Island', 'countryIsoCode2' => 'BV', 'countryIsoCode3' => 'BVT', 'countryStatus' => '1'],
            ['countryId' => '30', 'countryName' => 'Brazil', 'countryIsoCode2' => 'BR', 'countryIsoCode3' => 'BRA', 'countryStatus' => '1'],
            ['countryId' => '31', 'countryName' => 'British Indian Ocean Territory', 'countryIsoCode2' => 'IO', 'countryIsoCode3' => 'IOT', 'countryStatus' => '1'],
            ['countryId' => '32', 'countryName' => 'Brunei Darussalam', 'countryIsoCode2' => 'BN', 'countryIsoCode3' => 'BRN', 'countryStatus' => '1'],
            ['countryId' => '33', 'countryName' => 'Bulgaria', 'countryIsoCode2' => 'BG', 'countryIsoCode3' => 'BGR', 'countryStatus' => '1'],
            ['countryId' => '34', 'countryName' => 'Burkina Faso', 'countryIsoCode2' => 'BF', 'countryIsoCode3' => 'BFA', 'countryStatus' => '1'],
            ['countryId' => '35', 'countryName' => 'Burundi', 'countryIsoCode2' => 'BI', 'countryIsoCode3' => 'BDI', 'countryStatus' => '1'],
            ['countryId' => '36', 'countryName' => 'Cambodia', 'countryIsoCode2' => 'KH', 'countryIsoCode3' => 'KHM', 'countryStatus' => '1'],
            ['countryId' => '37', 'countryName' => 'Cameroon', 'countryIsoCode2' => 'CM', 'countryIsoCode3' => 'CMR', 'countryStatus' => '1'],
            ['countryId' => '38', 'countryName' => 'Canada', 'countryIsoCode2' => 'CA', 'countryIsoCode3' => 'CAN', 'countryStatus' => '1'],
            ['countryId' => '39', 'countryName' => 'Cape Verde', 'countryIsoCode2' => 'CV', 'countryIsoCode3' => 'CPV', 'countryStatus' => '1'],
            ['countryId' => '40', 'countryName' => 'Cayman Islands', 'countryIsoCode2' => 'KY', 'countryIsoCode3' => 'CYM', 'countryStatus' => '1'],
            ['countryId' => '41', 'countryName' => 'Central African Republic', 'countryIsoCode2' => 'CF', 'countryIsoCode3' => 'CAF', 'countryStatus' => '1'],
            ['countryId' => '42', 'countryName' => 'Chad', 'countryIsoCode2' => 'TD', 'countryIsoCode3' => 'TCD', 'countryStatus' => '1'],
            ['countryId' => '43', 'countryName' => 'Chile', 'countryIsoCode2' => 'CL', 'countryIsoCode3' => 'CHL', 'countryStatus' => '1'],
            ['countryId' => '44', 'countryName' => 'China', 'countryIsoCode2' => 'CN', 'countryIsoCode3' => 'CHN', 'countryStatus' => '1'],
            ['countryId' => '45', 'countryName' => 'Christmas Island', 'countryIsoCode2' => 'CX', 'countryIsoCode3' => 'CXR', 'countryStatus' => '1'],
            ['countryId' => '46', 'countryName' => 'Cocos (Keeling) Islands', 'countryIsoCode2' => 'CC', 'countryIsoCode3' => 'CCK', 'countryStatus' => '1'],
            ['countryId' => '47', 'countryName' => 'Colombia', 'countryIsoCode2' => 'CO', 'countryIsoCode3' => 'COL', 'countryStatus' => '1'],
            ['countryId' => '48', 'countryName' => 'Comoros', 'countryIsoCode2' => 'KM', 'countryIsoCode3' => 'COM', 'countryStatus' => '1'],
            ['countryId' => '49', 'countryName' => 'Congo', 'countryIsoCode2' => 'CG', 'countryIsoCode3' => 'COG', 'countryStatus' => '1'],
            ['countryId' => '50', 'countryName' => 'Cook Islands', 'countryIsoCode2' => 'CK', 'countryIsoCode3' => 'COK', 'countryStatus' => '1'],
            ['countryId' => '51', 'countryName' => 'Costa Rica', 'countryIsoCode2' => 'CR', 'countryIsoCode3' => 'CRI', 'countryStatus' => '1'],
            ['countryId' => '52', 'countryName' => 'Cote D\'Ivoire', 'countryIsoCode2' => 'CI', 'countryIsoCode3' => 'CIV', 'countryStatus' => '1'],
            ['countryId' => '53', 'countryName' => 'Croatia', 'countryIsoCode2' => 'HR', 'countryIsoCode3' => 'HRV', 'countryStatus' => '1'],
            ['countryId' => '54', 'countryName' => 'Cuba', 'countryIsoCode2' => 'CU', 'countryIsoCode3' => 'CUB', 'countryStatus' => '1'],
            ['countryId' => '55', 'countryName' => 'Cyprus', 'countryIsoCode2' => 'CY', 'countryIsoCode3' => 'CYP', 'countryStatus' => '1'],
            ['countryId' => '56', 'countryName' => 'Czech Republic', 'countryIsoCode2' => 'CZ', 'countryIsoCode3' => 'CZE', 'countryStatus' => '1'],
            ['countryId' => '57', 'countryName' => 'Denmark', 'countryIsoCode2' => 'DK', 'countryIsoCode3' => 'DNK', 'countryStatus' => '1'],
            ['countryId' => '58', 'countryName' => 'Djibouti', 'countryIsoCode2' => 'DJ', 'countryIsoCode3' => 'DJI', 'countryStatus' => '1'],
            ['countryId' => '59', 'countryName' => 'Dominica', 'countryIsoCode2' => 'DM', 'countryIsoCode3' => 'DMA', 'countryStatus' => '1'],
            ['countryId' => '60', 'countryName' => 'Dominican Republic', 'countryIsoCode2' => 'DO', 'countryIsoCode3' => 'DOM', 'countryStatus' => '1'],
            ['countryId' => '61', 'countryName' => 'East Timor', 'countryIsoCode2' => 'TL', 'countryIsoCode3' => 'TLS', 'countryStatus' => '1'],
            ['countryId' => '62', 'countryName' => 'Ecuador', 'countryIsoCode2' => 'EC', 'countryIsoCode3' => 'ECU', 'countryStatus' => '1'],
            ['countryId' => '63', 'countryName' => 'Egypt', 'countryIsoCode2' => 'EG', 'countryIsoCode3' => 'EGY', 'countryStatus' => '1'],
            ['countryId' => '64', 'countryName' => 'El Salvador', 'countryIsoCode2' => 'SV', 'countryIsoCode3' => 'SLV', 'countryStatus' => '1'],
            ['countryId' => '65', 'countryName' => 'Equatorial Guinea', 'countryIsoCode2' => 'GQ', 'countryIsoCode3' => 'GNQ', 'countryStatus' => '1'],
            ['countryId' => '66', 'countryName' => 'Eritrea', 'countryIsoCode2' => 'ER', 'countryIsoCode3' => 'ERI', 'countryStatus' => '1'],
            ['countryId' => '67', 'countryName' => 'Estonia', 'countryIsoCode2' => 'EE', 'countryIsoCode3' => 'EST', 'countryStatus' => '1'],
            ['countryId' => '68', 'countryName' => 'Ethiopia', 'countryIsoCode2' => 'ET', 'countryIsoCode3' => 'ETH', 'countryStatus' => '1'],
            ['countryId' => '69', 'countryName' => 'Falkland Islands (Malvinas)', 'countryIsoCode2' => 'FK', 'countryIsoCode3' => 'FLK', 'countryStatus' => '1'],
            ['countryId' => '70', 'countryName' => 'Faroe Islands', 'countryIsoCode2' => 'FO', 'countryIsoCode3' => 'FRO', 'countryStatus' => '1'],
            ['countryId' => '71', 'countryName' => 'Fiji', 'countryIsoCode2' => 'FJ', 'countryIsoCode3' => 'FJI', 'countryStatus' => '1'],
            ['countryId' => '72', 'countryName' => 'Finland', 'countryIsoCode2' => 'FI', 'countryIsoCode3' => 'FIN', 'countryStatus' => '1'],
            ['countryId' => '74', 'countryName' => 'France, Metropolitan', 'countryIsoCode2' => 'FR', 'countryIsoCode3' => 'FRA', 'countryStatus' => '1'],
            ['countryId' => '75', 'countryName' => 'French Guiana', 'countryIsoCode2' => 'GF', 'countryIsoCode3' => 'GUF', 'countryStatus' => '1'],
            ['countryId' => '76', 'countryName' => 'French Polynesia', 'countryIsoCode2' => 'PF', 'countryIsoCode3' => 'PYF', 'countryStatus' => '1'],
            ['countryId' => '77', 'countryName' => 'French Southern Territories', 'countryIsoCode2' => 'TF', 'countryIsoCode3' => 'ATF', 'countryStatus' => '1'],
            ['countryId' => '78', 'countryName' => 'Gabon', 'countryIsoCode2' => 'GA', 'countryIsoCode3' => 'GAB', 'countryStatus' => '1'],
            ['countryId' => '79', 'countryName' => 'Gambia', 'countryIsoCode2' => 'GM', 'countryIsoCode3' => 'GMB', 'countryStatus' => '1'],
            ['countryId' => '80', 'countryName' => 'Georgia', 'countryIsoCode2' => 'GE', 'countryIsoCode3' => 'GEO', 'countryStatus' => '1'],
            ['countryId' => '81', 'countryName' => 'Germany', 'countryIsoCode2' => 'DE', 'countryIsoCode3' => 'DEU', 'countryStatus' => '1'],
            ['countryId' => '82', 'countryName' => 'Ghana', 'countryIsoCode2' => 'GH', 'countryIsoCode3' => 'GHA', 'countryStatus' => '1'],
            ['countryId' => '83', 'countryName' => 'Gibraltar', 'countryIsoCode2' => 'GI', 'countryIsoCode3' => 'GIB', 'countryStatus' => '1'],
            ['countryId' => '84', 'countryName' => 'Greece', 'countryIsoCode2' => 'GR', 'countryIsoCode3' => 'GRC', 'countryStatus' => '1'],
            ['countryId' => '85', 'countryName' => 'Greenland', 'countryIsoCode2' => 'GL', 'countryIsoCode3' => 'GRL', 'countryStatus' => '1'],
            ['countryId' => '86', 'countryName' => 'Grenada', 'countryIsoCode2' => 'GD', 'countryIsoCode3' => 'GRD', 'countryStatus' => '1'],
            ['countryId' => '87', 'countryName' => 'Guadeloupe', 'countryIsoCode2' => 'GP', 'countryIsoCode3' => 'GLP', 'countryStatus' => '1'],
            ['countryId' => '88', 'countryName' => 'Guam', 'countryIsoCode2' => 'GU', 'countryIsoCode3' => 'GUM', 'countryStatus' => '1'],
            ['countryId' => '89', 'countryName' => 'Guatemala', 'countryIsoCode2' => 'GT', 'countryIsoCode3' => 'GTM', 'countryStatus' => '1'],
            ['countryId' => '90', 'countryName' => 'Guinea', 'countryIsoCode2' => 'GN', 'countryIsoCode3' => 'GIN', 'countryStatus' => '1'],
            ['countryId' => '91', 'countryName' => 'Guinea-Bissau', 'countryIsoCode2' => 'GW', 'countryIsoCode3' => 'GNB', 'countryStatus' => '1'],
            ['countryId' => '92', 'countryName' => 'Guyana', 'countryIsoCode2' => 'GY', 'countryIsoCode3' => 'GUY', 'countryStatus' => '1'],
            ['countryId' => '93', 'countryName' => 'Haiti', 'countryIsoCode2' => 'HT', 'countryIsoCode3' => 'HTI', 'countryStatus' => '1'],
            ['countryId' => '94', 'countryName' => 'Heard and Mc Donald Islands', 'countryIsoCode2' => 'HM', 'countryIsoCode3' => 'HMD', 'countryStatus' => '1'],
            ['countryId' => '95', 'countryName' => 'Honduras', 'countryIsoCode2' => 'HN', 'countryIsoCode3' => 'HND', 'countryStatus' => '1'],
            ['countryId' => '96', 'countryName' => 'Hong Kong', 'countryIsoCode2' => 'HK', 'countryIsoCode3' => 'HKG', 'countryStatus' => '1'],
            ['countryId' => '97', 'countryName' => 'Hungary', 'countryIsoCode2' => 'HU', 'countryIsoCode3' => 'HUN', 'countryStatus' => '1'],
            ['countryId' => '98', 'countryName' => 'Iceland', 'countryIsoCode2' => 'IS', 'countryIsoCode3' => 'ISL', 'countryStatus' => '1'],
            ['countryId' => '99', 'countryName' => 'India', 'countryIsoCode2' => 'IN', 'countryIsoCode3' => 'IND', 'countryStatus' => '1'],
            ['countryId' => '100', 'countryName' => 'Indonesia', 'countryIsoCode2' => 'ID', 'countryIsoCode3' => 'IDN', 'countryStatus' => '1'],
            ['countryId' => '101', 'countryName' => 'Iran (Islamic Republic of)', 'countryIsoCode2' => 'IR', 'countryIsoCode3' => 'IRN', 'countryStatus' => '1'],
            ['countryId' => '102', 'countryName' => 'Iraq', 'countryIsoCode2' => 'IQ', 'countryIsoCode3' => 'IRQ', 'countryStatus' => '1'],
            ['countryId' => '103', 'countryName' => 'Ireland', 'countryIsoCode2' => 'IE', 'countryIsoCode3' => 'IRL', 'countryStatus' => '1'],
            ['countryId' => '104', 'countryName' => 'Israel', 'countryIsoCode2' => 'IL', 'countryIsoCode3' => 'ISR', 'countryStatus' => '1'],
            ['countryId' => '105', 'countryName' => 'Italy', 'countryIsoCode2' => 'IT', 'countryIsoCode3' => 'ITA', 'countryStatus' => '1'],
            ['countryId' => '106', 'countryName' => 'Jamaica', 'countryIsoCode2' => 'JM', 'countryIsoCode3' => 'JAM', 'countryStatus' => '1'],
            ['countryId' => '107', 'countryName' => 'Japan', 'countryIsoCode2' => 'JP', 'countryIsoCode3' => 'JPN', 'countryStatus' => '1'],
            ['countryId' => '108', 'countryName' => 'Jordan', 'countryIsoCode2' => 'JO', 'countryIsoCode3' => 'JOR', 'countryStatus' => '1'],
            ['countryId' => '109', 'countryName' => 'Kazakhstan', 'countryIsoCode2' => 'KZ', 'countryIsoCode3' => 'KAZ', 'countryStatus' => '1'],
            ['countryId' => '110', 'countryName' => 'Kenya', 'countryIsoCode2' => 'KE', 'countryIsoCode3' => 'KEN', 'countryStatus' => '1'],
            ['countryId' => '111', 'countryName' => 'Kiribati', 'countryIsoCode2' => 'KI', 'countryIsoCode3' => 'KIR', 'countryStatus' => '1'],
            ['countryId' => '112', 'countryName' => 'North Korea', 'countryIsoCode2' => 'KP', 'countryIsoCode3' => 'PRK', 'countryStatus' => '1'],
            ['countryId' => '113', 'countryName' => 'South Korea', 'countryIsoCode2' => 'KR', 'countryIsoCode3' => 'KOR', 'countryStatus' => '1'],
            ['countryId' => '114', 'countryName' => 'Kuwait', 'countryIsoCode2' => 'KW', 'countryIsoCode3' => 'KWT', 'countryStatus' => '1'],
            ['countryId' => '115', 'countryName' => 'Kyrgyzstan', 'countryIsoCode2' => 'KG', 'countryIsoCode3' => 'KGZ', 'countryStatus' => '1'],
            ['countryId' => '116', 'countryName' => 'Lao People\'s Democratic Republic', 'countryIsoCode2' => 'LA', 'countryIsoCode3' => 'LAO', 'countryStatus' => '1'],
            ['countryId' => '117', 'countryName' => 'Latvia', 'countryIsoCode2' => 'LV', 'countryIsoCode3' => 'LVA', 'countryStatus' => '1'],
            ['countryId' => '118', 'countryName' => 'Lebanon', 'countryIsoCode2' => 'LB', 'countryIsoCode3' => 'LBN', 'countryStatus' => '1'],
            ['countryId' => '119', 'countryName' => 'Lesotho', 'countryIsoCode2' => 'LS', 'countryIsoCode3' => 'LSO', 'countryStatus' => '1'],
            ['countryId' => '120', 'countryName' => 'Liberia', 'countryIsoCode2' => 'LR', 'countryIsoCode3' => 'LBR', 'countryStatus' => '1'],
            ['countryId' => '121', 'countryName' => 'Libyan Arab Jamahiriya', 'countryIsoCode2' => 'LY', 'countryIsoCode3' => 'LBY', 'countryStatus' => '1'],
            ['countryId' => '122', 'countryName' => 'Liechtenstein', 'countryIsoCode2' => 'LI', 'countryIsoCode3' => 'LIE', 'countryStatus' => '1'],
            ['countryId' => '123', 'countryName' => 'Lithuania', 'countryIsoCode2' => 'LT', 'countryIsoCode3' => 'LTU', 'countryStatus' => '1'],
            ['countryId' => '124', 'countryName' => 'Luxembourg', 'countryIsoCode2' => 'LU', 'countryIsoCode3' => 'LUX', 'countryStatus' => '1'],
            ['countryId' => '125', 'countryName' => 'Macau', 'countryIsoCode2' => 'MO', 'countryIsoCode3' => 'MAC', 'countryStatus' => '1'],
            ['countryId' => '126', 'countryName' => 'FYROM', 'countryIsoCode2' => 'MK', 'countryIsoCode3' => 'MKD', 'countryStatus' => '1'],
            ['countryId' => '127', 'countryName' => 'Madagascar', 'countryIsoCode2' => 'MG', 'countryIsoCode3' => 'MDG', 'countryStatus' => '1'],
            ['countryId' => '128', 'countryName' => 'Malawi', 'countryIsoCode2' => 'MW', 'countryIsoCode3' => 'MWI', 'countryStatus' => '1'],
            ['countryId' => '129', 'countryName' => 'Malaysia', 'countryIsoCode2' => 'MY', 'countryIsoCode3' => 'MYS', 'countryStatus' => '1'],
            ['countryId' => '130', 'countryName' => 'Maldives', 'countryIsoCode2' => 'MV', 'countryIsoCode3' => 'MDV', 'countryStatus' => '1'],
            ['countryId' => '131', 'countryName' => 'Mali', 'countryIsoCode2' => 'ML', 'countryIsoCode3' => 'MLI', 'countryStatus' => '1'],
            ['countryId' => '132', 'countryName' => 'Malta', 'countryIsoCode2' => 'MT', 'countryIsoCode3' => 'MLT', 'countryStatus' => '1'],
            ['countryId' => '133', 'countryName' => 'Marshall Islands', 'countryIsoCode2' => 'MH', 'countryIsoCode3' => 'MHL', 'countryStatus' => '1'],
            ['countryId' => '134', 'countryName' => 'Martinique', 'countryIsoCode2' => 'MQ', 'countryIsoCode3' => 'MTQ', 'countryStatus' => '1'],
            ['countryId' => '135', 'countryName' => 'Mauritania', 'countryIsoCode2' => 'MR', 'countryIsoCode3' => 'MRT', 'countryStatus' => '1'],
            ['countryId' => '136', 'countryName' => 'Mauritius', 'countryIsoCode2' => 'MU', 'countryIsoCode3' => 'MUS', 'countryStatus' => '1'],
            ['countryId' => '137', 'countryName' => 'Mayotte', 'countryIsoCode2' => 'YT', 'countryIsoCode3' => 'MYT', 'countryStatus' => '1'],
            ['countryId' => '138', 'countryName' => 'Mexico', 'countryIsoCode2' => 'MX', 'countryIsoCode3' => 'MEX', 'countryStatus' => '1'],
            ['countryId' => '139', 'countryName' => 'Micronesia, Federated States of', 'countryIsoCode2' => 'FM', 'countryIsoCode3' => 'FSM', 'countryStatus' => '1'],
            ['countryId' => '140', 'countryName' => 'Moldova, Republic of', 'countryIsoCode2' => 'MD', 'countryIsoCode3' => 'MDA', 'countryStatus' => '1'],
            ['countryId' => '141', 'countryName' => 'Monaco', 'countryIsoCode2' => 'MC', 'countryIsoCode3' => 'MCO', 'countryStatus' => '1'],
            ['countryId' => '142', 'countryName' => 'Mongolia', 'countryIsoCode2' => 'MN', 'countryIsoCode3' => 'MNG', 'countryStatus' => '1'],
            ['countryId' => '143', 'countryName' => 'Montserrat', 'countryIsoCode2' => 'MS', 'countryIsoCode3' => 'MSR', 'countryStatus' => '1'],
            ['countryId' => '144', 'countryName' => 'Morocco', 'countryIsoCode2' => 'MA', 'countryIsoCode3' => 'MAR', 'countryStatus' => '1'],
            ['countryId' => '145', 'countryName' => 'Mozambique', 'countryIsoCode2' => 'MZ', 'countryIsoCode3' => 'MOZ', 'countryStatus' => '1'],
            ['countryId' => '146', 'countryName' => 'Myanmar', 'countryIsoCode2' => 'MM', 'countryIsoCode3' => 'MMR', 'countryStatus' => '1'],
            ['countryId' => '147', 'countryName' => 'Namibia', 'countryIsoCode2' => 'NA', 'countryIsoCode3' => 'NAM', 'countryStatus' => '1'],
            ['countryId' => '148', 'countryName' => 'Nauru', 'countryIsoCode2' => 'NR', 'countryIsoCode3' => 'NRU', 'countryStatus' => '1'],
            ['countryId' => '149', 'countryName' => 'Nepal', 'countryIsoCode2' => 'NP', 'countryIsoCode3' => 'NPL', 'countryStatus' => '1'],
            ['countryId' => '150', 'countryName' => 'Netherlands', 'countryIsoCode2' => 'NL', 'countryIsoCode3' => 'NLD', 'countryStatus' => '1'],
            ['countryId' => '151', 'countryName' => 'Netherlands Antilles', 'countryIsoCode2' => 'AN', 'countryIsoCode3' => 'ANT', 'countryStatus' => '1'],
            ['countryId' => '152', 'countryName' => 'New Caledonia', 'countryIsoCode2' => 'NC', 'countryIsoCode3' => 'NCL', 'countryStatus' => '1'],
            ['countryId' => '153', 'countryName' => 'New Zealand', 'countryIsoCode2' => 'NZ', 'countryIsoCode3' => 'NZL', 'countryStatus' => '1'],
            ['countryId' => '154', 'countryName' => 'Nicaragua', 'countryIsoCode2' => 'NI', 'countryIsoCode3' => 'NIC', 'countryStatus' => '1'],
            ['countryId' => '155', 'countryName' => 'Niger', 'countryIsoCode2' => 'NE', 'countryIsoCode3' => 'NER', 'countryStatus' => '1'],
            ['countryId' => '156', 'countryName' => 'Nigeria', 'countryIsoCode2' => 'NG', 'countryIsoCode3' => 'NGA', 'countryStatus' => '1'],
            ['countryId' => '157', 'countryName' => 'Niue', 'countryIsoCode2' => 'NU', 'countryIsoCode3' => 'NIU', 'countryStatus' => '1'],
            ['countryId' => '158', 'countryName' => 'Norfolk Island', 'countryIsoCode2' => 'NF', 'countryIsoCode3' => 'NFK', 'countryStatus' => '1'],
            ['countryId' => '159', 'countryName' => 'Northern Mariana Islands', 'countryIsoCode2' => 'MP', 'countryIsoCode3' => 'MNP', 'countryStatus' => '1'],
            ['countryId' => '160', 'countryName' => 'Norway', 'countryIsoCode2' => 'NO', 'countryIsoCode3' => 'NOR', 'countryStatus' => '1'],
            ['countryId' => '161', 'countryName' => 'Oman', 'countryIsoCode2' => 'OM', 'countryIsoCode3' => 'OMN', 'countryStatus' => '1'],
            ['countryId' => '162', 'countryName' => 'Pakistan', 'countryIsoCode2' => 'PK', 'countryIsoCode3' => 'PAK', 'countryStatus' => '1'],
            ['countryId' => '163', 'countryName' => 'Palau', 'countryIsoCode2' => 'PW', 'countryIsoCode3' => 'PLW', 'countryStatus' => '1'],
            ['countryId' => '164', 'countryName' => 'Panama', 'countryIsoCode2' => 'PA', 'countryIsoCode3' => 'PAN', 'countryStatus' => '1'],
            ['countryId' => '165', 'countryName' => 'Papua New Guinea', 'countryIsoCode2' => 'PG', 'countryIsoCode3' => 'PNG', 'countryStatus' => '1'],
            ['countryId' => '166', 'countryName' => 'Paraguay', 'countryIsoCode2' => 'PY', 'countryIsoCode3' => 'PRY', 'countryStatus' => '1'],
            ['countryId' => '167', 'countryName' => 'Peru', 'countryIsoCode2' => 'PE', 'countryIsoCode3' => 'PER', 'countryStatus' => '1'],
            ['countryId' => '168', 'countryName' => 'Philippines', 'countryIsoCode2' => 'PH', 'countryIsoCode3' => 'PHL', 'countryStatus' => '1'],
            ['countryId' => '169', 'countryName' => 'Pitcairn', 'countryIsoCode2' => 'PN', 'countryIsoCode3' => 'PCN', 'countryStatus' => '1'],
            ['countryId' => '170', 'countryName' => 'Poland', 'countryIsoCode2' => 'PL', 'countryIsoCode3' => 'POL', 'countryStatus' => '1'],
            ['countryId' => '171', 'countryName' => 'Portugal', 'countryIsoCode2' => 'PT', 'countryIsoCode3' => 'PRT', 'countryStatus' => '1'],
            ['countryId' => '172', 'countryName' => 'Puerto Rico', 'countryIsoCode2' => 'PR', 'countryIsoCode3' => 'PRI', 'countryStatus' => '1'],
            ['countryId' => '173', 'countryName' => 'Qatar', 'countryIsoCode2' => 'QA', 'countryIsoCode3' => 'QAT', 'countryStatus' => '1'],
            ['countryId' => '174', 'countryName' => 'Reunion', 'countryIsoCode2' => 'RE', 'countryIsoCode3' => 'REU', 'countryStatus' => '1'],
            ['countryId' => '175', 'countryName' => 'Romania', 'countryIsoCode2' => 'RO', 'countryIsoCode3' => 'ROM', 'countryStatus' => '1'],
            ['countryId' => '176', 'countryName' => 'Russian Federation', 'countryIsoCode2' => 'RU', 'countryIsoCode3' => 'RUS', 'countryStatus' => '1'],
            ['countryId' => '177', 'countryName' => 'Rwanda', 'countryIsoCode2' => 'RW', 'countryIsoCode3' => 'RWA', 'countryStatus' => '1'],
            ['countryId' => '178', 'countryName' => 'Saint Kitts and Nevis', 'countryIsoCode2' => 'KN', 'countryIsoCode3' => 'KNA', 'countryStatus' => '1'],
            ['countryId' => '179', 'countryName' => 'Saint Lucia', 'countryIsoCode2' => 'LC', 'countryIsoCode3' => 'LCA', 'countryStatus' => '1'],
            ['countryId' => '180', 'countryName' => 'Saint Vincent and the Grenadines', 'countryIsoCode2' => 'VC', 'countryIsoCode3' => 'VCT', 'countryStatus' => '1'],
            ['countryId' => '181', 'countryName' => 'Samoa', 'countryIsoCode2' => 'WS', 'countryIsoCode3' => 'WSM', 'countryStatus' => '1'],
            ['countryId' => '182', 'countryName' => 'San Marino', 'countryIsoCode2' => 'SM', 'countryIsoCode3' => 'SMR', 'countryStatus' => '1'],
            ['countryId' => '183', 'countryName' => 'Sao Tome and Principe', 'countryIsoCode2' => 'ST', 'countryIsoCode3' => 'STP', 'countryStatus' => '1'],
            ['countryId' => '184', 'countryName' => 'Saudi Arabia', 'countryIsoCode2' => 'SA', 'countryIsoCode3' => 'SAU', 'countryStatus' => '1'],
            ['countryId' => '185', 'countryName' => 'Senegal', 'countryIsoCode2' => 'SN', 'countryIsoCode3' => 'SEN', 'countryStatus' => '1'],
            ['countryId' => '186', 'countryName' => 'Seychelles', 'countryIsoCode2' => 'SC', 'countryIsoCode3' => 'SYC', 'countryStatus' => '1'],
            ['countryId' => '187', 'countryName' => 'Sierra Leone', 'countryIsoCode2' => 'SL', 'countryIsoCode3' => 'SLE', 'countryStatus' => '1'],
            ['countryId' => '188', 'countryName' => 'Singapore', 'countryIsoCode2' => 'SG', 'countryIsoCode3' => 'SGP', 'countryStatus' => '1'],
            ['countryId' => '189', 'countryName' => 'Slovak Republic', 'countryIsoCode2' => 'SK', 'countryIsoCode3' => 'SVK', 'countryStatus' => '1'],
            ['countryId' => '190', 'countryName' => 'Slovenia', 'countryIsoCode2' => 'SI', 'countryIsoCode3' => 'SVN', 'countryStatus' => '1'],
            ['countryId' => '191', 'countryName' => 'Solomon Islands', 'countryIsoCode2' => 'SB', 'countryIsoCode3' => 'SLB', 'countryStatus' => '1'],
            ['countryId' => '192', 'countryName' => 'Somalia', 'countryIsoCode2' => 'SO', 'countryIsoCode3' => 'SOM', 'countryStatus' => '1'],
            ['countryId' => '193', 'countryName' => 'South Africa', 'countryIsoCode2' => 'ZA', 'countryIsoCode3' => 'ZAF', 'countryStatus' => '1'],
            ['countryId' => '194', 'countryName' => 'South Georgia &amp; South Sandwich Islands', 'countryIsoCode2' => 'GS', 'countryIsoCode3' => 'SGS', 'countryStatus' => '1'],
            ['countryId' => '195', 'countryName' => 'Spain', 'countryIsoCode2' => 'ES', 'countryIsoCode3' => 'ESP', 'countryStatus' => '1'],
            ['countryId' => '196', 'countryName' => 'Sri Lanka', 'countryIsoCode2' => 'LK', 'countryIsoCode3' => 'LKA', 'countryStatus' => '1'],
            ['countryId' => '197', 'countryName' => 'St. Helena', 'countryIsoCode2' => 'SH', 'countryIsoCode3' => 'SHN', 'countryStatus' => '1'],
            ['countryId' => '198', 'countryName' => 'St. Pierre and Miquelon', 'countryIsoCode2' => 'PM', 'countryIsoCode3' => 'SPM', 'countryStatus' => '1'],
            ['countryId' => '199', 'countryName' => 'Sudan', 'countryIsoCode2' => 'SD', 'countryIsoCode3' => 'SDN', 'countryStatus' => '1'],
            ['countryId' => '200', 'countryName' => 'Suriname', 'countryIsoCode2' => 'SR', 'countryIsoCode3' => 'SUR', 'countryStatus' => '1'],
            ['countryId' => '201', 'countryName' => 'Svalbard and Jan Mayen Islands', 'countryIsoCode2' => 'SJ', 'countryIsoCode3' => 'SJM', 'countryStatus' => '1'],
            ['countryId' => '202', 'countryName' => 'Swaziland', 'countryIsoCode2' => 'SZ', 'countryIsoCode3' => 'SWZ', 'countryStatus' => '1'],
            ['countryId' => '203', 'countryName' => 'Sweden', 'countryIsoCode2' => 'SE', 'countryIsoCode3' => 'SWE', 'countryStatus' => '1'],
            ['countryId' => '204', 'countryName' => 'Switzerland', 'countryIsoCode2' => 'CH', 'countryIsoCode3' => 'CHE', 'countryStatus' => '1'],
            ['countryId' => '205', 'countryName' => 'Syrian Arab Republic', 'countryIsoCode2' => 'SY', 'countryIsoCode3' => 'SYR', 'countryStatus' => '1'],
            ['countryId' => '206', 'countryName' => 'Taiwan', 'countryIsoCode2' => 'TW', 'countryIsoCode3' => 'TWN', 'countryStatus' => '1'],
            ['countryId' => '207', 'countryName' => 'Tajikistan', 'countryIsoCode2' => 'TJ', 'countryIsoCode3' => 'TJK', 'countryStatus' => '1'],
            ['countryId' => '208', 'countryName' => 'Tanzania, United Republic of', 'countryIsoCode2' => 'TZ', 'countryIsoCode3' => 'TZA', 'countryStatus' => '1'],
            ['countryId' => '209', 'countryName' => 'Thailand', 'countryIsoCode2' => 'TH', 'countryIsoCode3' => 'THA', 'countryStatus' => '1'],
            ['countryId' => '210', 'countryName' => 'Togo', 'countryIsoCode2' => 'TG', 'countryIsoCode3' => 'TGO', 'countryStatus' => '1'],
            ['countryId' => '211', 'countryName' => 'Tokelau', 'countryIsoCode2' => 'TK', 'countryIsoCode3' => 'TKL', 'countryStatus' => '1'],
            ['countryId' => '212', 'countryName' => 'Tonga', 'countryIsoCode2' => 'TO', 'countryIsoCode3' => 'TON', 'countryStatus' => '1'],
            ['countryId' => '213', 'countryName' => 'Trinidad and Tobago', 'countryIsoCode2' => 'TT', 'countryIsoCode3' => 'TTO', 'countryStatus' => '1'],
            ['countryId' => '214', 'countryName' => 'Tunisia', 'countryIsoCode2' => 'TN', 'countryIsoCode3' => 'TUN', 'countryStatus' => '1'],
            ['countryId' => '215', 'countryName' => 'Turkey', 'countryIsoCode2' => 'TR', 'countryIsoCode3' => 'TUR', 'countryStatus' => '1'],
            ['countryId' => '216', 'countryName' => 'Turkmenistan', 'countryIsoCode2' => 'TM', 'countryIsoCode3' => 'TKM', 'countryStatus' => '1'],
            ['countryId' => '217', 'countryName' => 'Turks and Caicos Islands', 'countryIsoCode2' => 'TC', 'countryIsoCode3' => 'TCA', 'countryStatus' => '1'],
            ['countryId' => '218', 'countryName' => 'Tuvalu', 'countryIsoCode2' => 'TV', 'countryIsoCode3' => 'TUV', 'countryStatus' => '1'],
            ['countryId' => '219', 'countryName' => 'Uganda', 'countryIsoCode2' => 'UG', 'countryIsoCode3' => 'UGA', 'countryStatus' => '1'],
            ['countryId' => '220', 'countryName' => 'Ukraine', 'countryIsoCode2' => 'UA', 'countryIsoCode3' => 'UKR', 'countryStatus' => '1'],
            ['countryId' => '221', 'countryName' => 'United Arab Emirates', 'countryIsoCode2' => 'AE', 'countryIsoCode3' => 'ARE', 'countryStatus' => '1'],
            ['countryId' => '222', 'countryName' => 'United Kingdom', 'countryIsoCode2' => 'GB', 'countryIsoCode3' => 'GBR', 'countryStatus' => '1'],
            ['countryId' => '223', 'countryName' => 'United States', 'countryIsoCode2' => 'US', 'countryIsoCode3' => 'USA', 'countryStatus' => '1'],
            ['countryId' => '224', 'countryName' => 'United States Minor Outlying Islands', 'countryIsoCode2' => 'UM', 'countryIsoCode3' => 'UMI', 'countryStatus' => '1'],
            ['countryId' => '225', 'countryName' => 'Uruguay', 'countryIsoCode2' => 'UY', 'countryIsoCode3' => 'URY', 'countryStatus' => '1'],
            ['countryId' => '226', 'countryName' => 'Uzbekistan', 'countryIsoCode2' => 'UZ', 'countryIsoCode3' => 'UZB', 'countryStatus' => '1'],
            ['countryId' => '227', 'countryName' => 'Vanuatu', 'countryIsoCode2' => 'VU', 'countryIsoCode3' => 'VUT', 'countryStatus' => '1'],
            ['countryId' => '228', 'countryName' => 'Vatican City State (Holy See)', 'countryIsoCode2' => 'VA', 'countryIsoCode3' => 'VAT', 'countryStatus' => '1'],
            ['countryId' => '229', 'countryName' => 'Venezuela', 'countryIsoCode2' => 'VE', 'countryIsoCode3' => 'VEN', 'countryStatus' => '1'],
            ['countryId' => '230', 'countryName' => 'Viet Nam', 'countryIsoCode2' => 'VN', 'countryIsoCode3' => 'VNM', 'countryStatus' => '1'],
            ['countryId' => '231', 'countryName' => 'Virgin Islands (British)', 'countryIsoCode2' => 'VG', 'countryIsoCode3' => 'VGB', 'countryStatus' => '1'],
            ['countryId' => '232', 'countryName' => 'Virgin Islands (U.S.)', 'countryIsoCode2' => 'VI', 'countryIsoCode3' => 'VIR', 'countryStatus' => '1'],
            ['countryId' => '233', 'countryName' => 'Wallis and Futuna Islands', 'countryIsoCode2' => 'WF', 'countryIsoCode3' => 'WLF', 'countryStatus' => '1'],
            ['countryId' => '234', 'countryName' => 'Western Sahara', 'countryIsoCode2' => 'EH', 'countryIsoCode3' => 'ESH', 'countryStatus' => '1'],
            ['countryId' => '235', 'countryName' => 'Yemen', 'countryIsoCode2' => 'YE', 'countryIsoCode3' => 'YEM', 'countryStatus' => '1'],
            ['countryId' => '237', 'countryName' => 'Democratic Republic of Congo', 'countryIsoCode2' => 'CD', 'countryIsoCode3' => 'COD', 'countryStatus' => '1'],
            ['countryId' => '238', 'countryName' => 'Zambia', 'countryIsoCode2' => 'ZM', 'countryIsoCode3' => 'ZMB', 'countryStatus' => '1'],
            ['countryId' => '239', 'countryName' => 'Zimbabwe', 'countryIsoCode2' => 'ZW', 'countryIsoCode3' => 'ZWE', 'countryStatus' => '1'],
            ['countryId' => '242', 'countryName' => 'Montenegro', 'countryIsoCode2' => 'ME', 'countryIsoCode3' => 'MNE', 'countryStatus' => '1'],
            ['countryId' => '243', 'countryName' => 'Serbia', 'countryIsoCode2' => 'RS', 'countryIsoCode3' => 'SRB', 'countryStatus' => '1'],
            ['countryId' => '244', 'countryName' => 'Aaland Islands', 'countryIsoCode2' => 'AX', 'countryIsoCode3' => 'ALA', 'countryStatus' => '1'],
            ['countryId' => '245', 'countryName' => 'Bonaire, Sint Eustatius and Saba', 'countryIsoCode2' => 'BQ', 'countryIsoCode3' => 'BES', 'countryStatus' => '1'],
            ['countryId' => '246', 'countryName' => 'Curacao', 'countryIsoCode2' => 'CW', 'countryIsoCode3' => 'CUW', 'countryStatus' => '1'],
            ['countryId' => '247', 'countryName' => 'Palestinian Territory, Occupied', 'countryIsoCode2' => 'PS', 'countryIsoCode3' => 'PSE', 'countryStatus' => '1'],
            ['countryId' => '248', 'countryName' => 'South Sudan', 'countryIsoCode2' => 'SS', 'countryIsoCode3' => 'SSD', 'countryStatus' => '1'],
            ['countryId' => '249', 'countryName' => 'St. Barthelemy', 'countryIsoCode2' => 'BL', 'countryIsoCode3' => 'BLM', 'countryStatus' => '1'],
            ['countryId' => '250', 'countryName' => 'St. Martin (French part)', 'countryIsoCode2' => 'MF', 'countryIsoCode3' => 'MAF', 'countryStatus' => '1'],
            ['countryId' => '251', 'countryName' => 'Canary Islands', 'countryIsoCode2' => 'IC', 'countryIsoCode3' => 'ICA', 'countryStatus' => '1'],
            ['countryId' => '252', 'countryName' => 'Ascension Island (British)', 'countryIsoCode2' => 'AC', 'countryIsoCode3' => 'ASC', 'countryStatus' => '1'],
            ['countryId' => '253', 'countryName' => 'Kosovo, Republic of', 'countryIsoCode2' => 'XK', 'countryIsoCode3' => 'UNK', 'countryStatus' => '1'],
            ['countryId' => '254', 'countryName' => 'Isle of Man', 'countryIsoCode2' => 'IM', 'countryIsoCode3' => 'IMN', 'countryStatus' => '1'],
            ['countryId' => '255', 'countryName' => 'Tristan da Cunha', 'countryIsoCode2' => 'TA', 'countryIsoCode3' => 'SHN', 'countryStatus' => '1'],
            ['countryId' => '256', 'countryName' => 'Guernsey', 'countryIsoCode2' => 'GG', 'countryIsoCode3' => 'GGY', 'countryStatus' => '1'],
            ['countryId' => '257', 'countryName' => 'Jersey', 'countryIsoCode2' => 'JE', 'countryIsoCode3' => 'JEY', 'countryStatus' => '1']
        ];
		return $arr;
	}

}

