<?php
	/*
		CREATED ON : 18/12/19 19:52:18
		SALT : gl,i)(d]!qfKlq85p$Iwe4DT$nOLq+<s
		PACKAGE : 

		ADMINDIRECTORY : memo_admin
		SERIALNUMBER : AFWSp29lAqqoAMs7BQFQFMPD4foDl3Fv
		EXPIRE : 0
		PACKAGE : 
		DOMAIN : memo_framework, memoframework, memo-framework
		MOBILE : on
		LANGUAGE : en_US, id_ID
	*/

	$license2016 = "TlZMWXZCeWRVNy9hWERqdWRLNGViZWhicTdNVlFxUHUvdzkwck1xQ0luYU1qdG8yRW9oVEFuL2ozem9YUGZ0ektJSXU2YUN4Z1VMZ2RpOCtBOTh4MXRPMHEvNnVndjFDKzZRSGVkTmxoTytyZGN2S0VRV0ZOVWp4QlVjMHJUVXRBY05lS3N0VUJ0SkV3LzN6cXRZWm1Wbnlvc1UzdWYvNWhkckR3UnJ0SHB3NnlaeU5QYzYvYUpFVFVEWGt6TkNHWkxhVFFXYzhBVzRTblZXZVorcXo1MUt5ZnJpZnVzUFE2ZnhCdEx2VUdEbmVyUEpnOGNBMmVlbzJEeitaajNJOXoxdE5VckUxQ1NldThPazEra25KUTRYU2ZhUm5aUThxWmpFbFFaejRkMXRaeTE2YW9WV3BveDh0NFdLbXNkSFJnTytma0h3QUZtZURMVlVmZFlqZEo4SzNjaTBzUmlFdVg5djF1Y0FWS0g0ekRaeUJIODZEOGM5ejdzK1VseDM2cGgxUkFKZ1VXM0xpWXFrTVhHTy8vWUJYYXIxczliaGdYYzhrNTRjdjBFMD0%3D";
?>
